### ISSUE TITLE
studio_pref.py is missing from the repo

### ISSUE THREAD

**Issue by ikrima** [LaidlawFX/LaidlawFX#1]
Thanks for sharing these. I've been using them as a way to learn how to setup houdini hdas.

I notice that studio_pref is missing; it's referenced in various hdas. 
Ex: sop vertex anim textures

`from LaidlawFX import studio_pref`
`studio_pref.oncreate(kwargs)`

**Comment by LaidlawFX** [comment]
Glad they are of use to you.
Yup I certainly forgot to submit the file. I just did now. Plus I turned on notification, lol.

**Comment by ikrima** [comment]
No worries! Same with my repos. Thanks again for putting these up
